version: "3"

services:
  api:
    container_name: carShop-api
    image: node:lts
    working_dir: /usr/src/api
    restart: always
    command: sh -c "yarn --only=prod && yarn start:prod"
    volumes:
      - ./src:/usr/src/api/src
      - ./dist/:/usr/src/api/dist
      - ./package.json:/usr/src/api/package.json
      - ./yarn.lock:/usr/src/api/yarn.lock
      - ./ormconfig.js:/usr/src/api/ormconfig.js
      - ./tsconfig.json:/usr/src/api/tsconfig.json
      - ./tsconfig.build.json:/usr/src/api/tsconfig.build.json
    env_file:
      - .env
    ports:
      - 3333:3333
    links:
      - postgres

  postgres:
    container_name: carShop-postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
